# Usage: uv run capx/envs/launch.py --config-path env_configs/cube_lifting/franka_robosuite_cube_lifting_multiturn_vdm_reduced_api_skill_lib.yaml

env:
  _target_: capx.envs.tasks.franka.franka_lift.FrankaLiftCodeEnv
  cfg:
    _target_: capx.envs.tasks.base.CodeExecEnvConfig
    low_level: franka_robosuite_cube_lift_low_level
    privileged: false
    viser_debug: true  # enable per-trial observation history + slider in Viser
    apis:
      - FrankaControlApiReducedSkillLibrary
    prompt: |
      You are controlling a Franka Emika robot with API described below.
      Goal: pick up the red cube and lift it.
      You may write python code comments for reasoning but ONLY write the executable Python code and do not write it in code fences.
      After this code executes, you will receive the current console stdout and stderr (any errors or print statements made in the code). You will then have the chance to write new code to query the environment state and/or complete the task.
      The functions (APIs) below are already imported to the environment. If you want to use numpy, you need to import it explicitly.
    
    multi_turn_prompt: |
      The following code blocks were just executed:
      ```python
      {executed_code}
      ```
      The current console stdout is:
      ```
      {console_stdout}
      ```
      The current console stderr is:
      ```
      {console_stderr}
      ```
      If there were no errors during compilation or execution, the console stderr will be empty. If there were errors, consider regenerating the code.
      Consider querying the environment state through perception-based tool calls and prints to see if the task is completed.
      Please respond with EXACTLY ONE of the following:
      - The word 'REGENERATE' followed immediately by new Python code in a fenced code block (```python...```) if you want to modify the code.
      - The word 'FINISH' if the task appears to be complete

api_servers:
  - _target_: capx.serving.launch_sam3_server.main
    device: cuda
    port: 8114
    host: 127.0.0.1
    
  - _target_: capx.serving.launch_contact_graspnet_server.main
    port: 8115
    host: 127.0.0.1
    
  - _target_: capx.serving.launch_pyroki_server.main
    port: 8116
    host: 127.0.0.1
    robot: panda_description
    target_link: panda_hand
    
record_video: true
output_dir: ./outputs/franka_robosuite_cube_lifting_multiturn_vdm_reduced_api_skill_lib
use_img_differencing: true

trials: 100
num_workers: 12