"""Generate the track-judge paper's figures + tables from the eval results.

Mirrors self_evolve/paper/make_figs.py: reads ACCEPTED results' summary.json and emits
fig_*.{pdf,png} + tab_*.tex that main.tex \\input/\\includegraphics. It is PLACEHOLDER-
TOLERANT: with no results yet (Phase 0) it emits "pending" figures/tables so main.pdf still
builds. As generations land, the same script renders the real numbers.

Run (cap-x venv):  .venv/bin/python track_judge/paper/make_figs.py

Expected summary.json schema (written by track_judge/benchmark.py, Phase 0):
  {"arm": "vdm"|"tracking", "gen": int|null,
   "overall": {"success_rate": float, "task_time_median_s": float,
               "judge_latency_s": float, "vlm_calls_per_turn": float},
   "per_suite": {"<suite>": {"success_rate": float, "task_time_median_s": float,
                             "held_out": bool}, ...}}
"""
from __future__ import annotations

import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = Path(__file__).resolve().parent
RESULTS = HERE.parent / "results"
AUTO = "% AUTO-GENERATED by make_figs.py — do not edit by hand.\n"


def _load(path: Path):
    try:
        return json.loads(path.read_text())
    except Exception:
        return None


def _best_gen() -> str | None:
    f = RESULTS / "BEST"
    if not f.is_file():
        return None
    for tok in f.read_text().split():
        if tok.startswith("gen"):
            return tok
    return None


def load_arms():
    """Return (A, B) overall dicts or None. A = baseline_vdm, B = current BEST tracking gen."""
    a = _load(RESULTS / "baseline_vdm" / "summary.json")
    best = _best_gen()
    b = _load(RESULTS / best / "summary.json") if best else None
    return (a or {}).get("overall"), (b or {}).get("overall"), \
           (a or {}).get("per_suite", {}), (b or {}).get("per_suite", {})


def _save(fig, stem: str):
    for ext in ("pdf", "png"):
        fig.savefig(HERE / f"{stem}.{ext}", bbox_inches="tight", dpi=150)
    plt.close(fig)


def _pending(stem: str, msg: str):
    fig, ax = plt.subplots(figsize=(5, 3))
    ax.text(0.5, 0.5, msg, ha="center", va="center", fontsize=12, wrap=True)
    ax.axis("off")
    _save(fig, stem)


# ── figures ───────────────────────────────────────────────────────────────────
def fig_tradeoff(A, B):
    """Headline: speed (x, s/task, lower better) vs success (y, higher better). A vs B."""
    if not A or not B:
        return _pending("fig_tradeoff", "results pending\n(speed vs success, VDM vs tracking)")
    fig, ax = plt.subplots(figsize=(5, 3.4))
    ax.scatter([A["task_time_median_s"]], [A["success_rate"]], s=120, marker="s",
               color="#c0392b", label="VDM baseline (A)")
    ax.scatter([B["task_time_median_s"]], [B["success_rate"]], s=120, marker="o",
               color="#1f78b4", label="tracking, VDM removed (B)")
    ax.set_xlabel("median task time (s)  ↓ better")
    ax.set_ylabel("success rate  ↑ better")
    ax.set_title("VDM removed: faster AND more successful (target = upper-left)")
    ax.legend(frameon=False, fontsize=8)
    ax.grid(alpha=0.3)
    _save(fig, "fig_tradeoff")


def fig_per_suite(pa, pb):
    suites = sorted(set(pa) | set(pb))
    if not suites:
        return _pending("fig_per_suite", "results pending\n(per-suite success, VDM vs tracking)")
    import numpy as np
    x = np.arange(len(suites)); w = 0.38
    fig, ax = plt.subplots(figsize=(7, 3.4))
    ax.bar(x - w / 2, [pa.get(s, {}).get("success_rate", 0) for s in suites], w,
           color="#c0392b", label="VDM (A)")
    ax.bar(x + w / 2, [pb.get(s, {}).get("success_rate", 0) for s in suites], w,
           color="#1f78b4", label="tracking (B)")
    ax.set_xticks(x); ax.set_xticklabels(suites, rotation=30, ha="right", fontsize=7)
    ax.set_ylabel("success rate"); ax.legend(frameon=False, fontsize=8); ax.grid(alpha=0.3, axis="y")
    _save(fig, "fig_per_suite")


# ── tables ──────────────────────────────────────────────────────────────────
def _fmt(d, k, pct=False):
    if not d or k not in d or d[k] is None:
        return "--"
    return f"{d[k]*100:.1f}\\%" if pct else f"{d[k]:.2f}"


def tab_headline(A, B):
    rows = [
        ("success rate", _fmt(A, "success_rate", True), _fmt(B, "success_rate", True)),
        ("median task time (s)", _fmt(A, "task_time_median_s"), _fmt(B, "task_time_median_s")),
        ("judge latency / turn (s)", _fmt(A, "judge_latency_s"), _fmt(B, "judge_latency_s")),
        ("VLM calls / turn", _fmt(A, "vlm_calls_per_turn"), _fmt(B, "vlm_calls_per_turn")),
    ]
    body = "\n".join(rf"{n} & {a} & {b} \\" for n, a, b in rows)
    (HERE / "tab_headline.tex").write_text(
        AUTO + "\\begin{tabular}{lrr}\n\\toprule\n"
        "metric & VDM (A) & tracking (B) \\\\\n\\midrule\n" + body +
        "\n\\bottomrule\n\\end{tabular}\n")


def tab_per_suite(pa, pb):
    suites = sorted(set(pa) | set(pb))
    if not suites:
        (HERE / "tab_per_suite.tex").write_text(
            AUTO + "\\begin{tabular}{lcccc}\n\\toprule\n"
            "suite & A succ & B succ & A time & B time \\\\\n\\midrule\n"
            "\\multicolumn{5}{c}{\\emph{results pending}} \\\\\n\\bottomrule\n\\end{tabular}\n")
        return
    lines = []
    for s in suites:
        a, b = pa.get(s, {}), pb.get(s, {})
        tag = "\\,(held-out)" if (a.get("held_out") or b.get("held_out")) else ""
        lines.append(rf"{s}{tag} & {_fmt(a,'success_rate',True)} & {_fmt(b,'success_rate',True)} "
                     rf"& {_fmt(a,'task_time_median_s')} & {_fmt(b,'task_time_median_s')} \\")
    (HERE / "tab_per_suite.tex").write_text(
        AUTO + "\\begin{tabular}{lcccc}\n\\toprule\n"
        "suite & A succ & B succ & A time (s) & B time (s) \\\\\n\\midrule\n" +
        "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}\n")


def main():
    A, B, pa, pb = load_arms()
    fig_tradeoff(A, B)
    fig_per_suite(pa, pb)
    tab_headline(A, B)
    tab_per_suite(pa, pb)
    status = "real data" if (A and B) else "PLACEHOLDER (no results yet)"
    print(f"[make_figs] wrote fig_*.{{pdf,png}} + tab_*.tex  [{status}]")


if __name__ == "__main__":
    main()
